#!/bin/sh
set -e

[ -c /dev/console ] || {
  echo "ERROR: /dev/console is missing or not a character device" >&2
  exit 1
}

[ -c /dev/null ] || {
  echo "ERROR: /dev/null is missing or not a character device" >&2
  exit 1
}

exec </dev/console >/dev/console 2>&1

mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

echo ""
echo "=== Buckyball RISC-V Linux ==="
echo ""
exec /bin/sh -i

# if you want to run workload automatically, you can remove the 'exec /bin/sh'
# and add the following lines to the end of the file:
# /root/xxx-linux
# echo "WORKLOAD_DONE"
# poweroff -f
